export const districts = [
  {id:"0", name:"All Island"},
  {id:"1", name:"Colombo"},
  {id:"2", name:"Gampaha"},
  {id:"3", name:"Kalutara"},
  {id:"4", name:"Kandy"},
  {id:"5", name:"Matale"},
  {id:"6", name:"Nuwara-Eliya"},
  {id:"7", name:"Galle"},
  {id:"8", name:"Matara"},
  {id:"9", name:"Hambantota"},
  {id:"10", name:"Jaffna"},
  {id:"11", name:"Vanni"},
  {id:"12", name:"Batticaloa"},
  {id:"13", name:"Digamadulla"},
  {id:"14", name:"Trincomalee"},
  {id:"15", name:"Kurunegala"},
  {id:"16", name:"Puttalam"},
  {id:"17", name:"Anuradapura"},
  {id:"18", name:"Polonnaruwa"},
  {id:"19", name:"Badulla"},
  {id:"20", name:"Moneragala"},
  {id:"21", name:"Ratnapura"},
  {id:"22", name:"Kegalle"},
];

export const divisions = {
  1 : [ // Colombo
    {id: 101, name: "Avissawella"},
    {id: 102, name: "Borella"},
    {id: 103, name: "Colombo-Central"},
    {id: 104, name: "Colombo-East"},
    {id: 105, name: "Colombo-North"},
    {id: 106, name: "Colombo-West"},
    {id: 107, name: "Dehiwala"},
    {id: 108, name: "Homagama"},
    {id: 109, name: "Kaduwela"},
    {id: 110, name: "Kesbewa"},
    {id: 111, name: "Kolonnawa"},
    {id: 112, name: "Kotte"},
    {id: 113, name: "Maharagama"},
    {id: 114, name: "Moratuwa"},
    {id: 115, name: "Ratmalana"},
    {id: 116, name: "Postal"},
  ],
  2 : [ // Gampaha
    {id: 201, name: "Attanagalla"},
    {id: 202, name: "Biyagama"},
    {id: 203, name: "Divulapitiya"},
    {id: 204, name: "Dompe"},
    {id: 205, name: "Gampaha"},
    {id: 206, name: "Ja-Ela"},
    {id: 207, name: "Katana"},
    {id: 208, name: "Kelaniya"},
    {id: 209, name: "Mahara"},
    {id: 210, name: "Minuwangoda"},
    {id: 211, name: "Mirigama"},
    {id: 212, name: "Negombo"},
    {id: 213, name: "Wattala"},
    {id: 214, name: "Postal"},
  ],
  3 : [ // Kalutara
    {id: 301, name: "Agalawatta"},
    {id: 302, name: "Bandaragama"},
    {id: 303, name: "Beruwala"},
    {id: 304, name: "Bulathsinhala"},
    {id: 305, name: "Horana"},
    {id: 306, name: "Kalutara"},
    {id: 307, name: "Matugama"},
    {id: 308, name: "Panadura"},
    {id: 309, name: "Postal"},
  ],
  4 : [ // Mahanuwara
    {id: 401, name: "Galagedara"},
    {id: 402, name: "Gampola"},
    {id: 403, name: "Harispattuwa"},
    {id: 404, name: "Hewaheta"},
    {id: 405, name: "Kundasale"},
    {id: 406, name: "Mahanuwara"},
    {id: 407, name: "Nawalapitiya"},
    {id: 408, name: "Pathadumbara"},
    {id: 409, name: "Senkadagala"},
    {id: 410, name: "Teldeniya"},
    {id: 411, name: "Ududumbara"},
    {id: 412, name: "Udunuwara"},
    {id: 413, name: "Yatinuwara"},
    {id: 414, name: "Postal"},
  ],
  5 : [ // Matale
    {id: 501, name: "Dambulla"},
    {id: 502, name: "Laggala"},
    {id: 503, name: "Matale"},
    {id: 504, name: "Rattota"},
    {id: 505, name: "Postal"},
  ],
  6 : [ // NuwaraEliya
    {id: 601, name: "Hanguranketha"},
    {id: 602, name: "Kotmale"},
    {id: 603, name: "NuwaraEliya-Maskeliya"},
    {id: 604, name: "Walapane"},
    {id: 605, name: "Postal"},
  ],
  7 : [ // Galle
    {id: 701, name: "Akmeemana"},
    {id: 702, name: "Ambalangoda"},
    {id: 703, name: "Baddegama"},
    {id: 704, name: "Balapitiya"},
    {id: 705, name: "Bentara-Elpitiya"},
    {id: 706, name: "Galle"},
    {id: 707, name: "Habaraduwa"},
    {id: 708, name: "Hiniduma"},
    {id: 709, name: "Karandeniya"},
    {id: 710, name: "Ratgama"},
    {id: 711, name: "Postal"},
  ],
  8 : [ // Matara
    {id: 801, name: "Akuressa"},
    {id: 802, name: "Deniyaya"},
    {id: 803, name: "Devinuwara"},
    {id: 804, name: "Hakmana"},
    {id: 805, name: "Kamburupitiya"},
    {id: 806, name: "Matara"},
    {id: 807, name: "Weligama"},
    {id: 808, name: "Postal"},
  ],
  9 : [ // Hambantota
    {id: 901, name: "Beliatta"},
    {id: 902, name: "Mulkirigala"},
    {id: 903, name: "Tangalle"},
    {id: 904, name: "Tissamaharama"},
    {id: 905, name: "Postal"},
  ],
  10 : [ // Jaffna
    {id: 1001, name: "Chavakachcheri"},
    {id: 1002, name: "Jaffna"},
    {id: 1003, name: "Kankesanturai"},
    {id: 1004, name: "Kayts"},
    {id: 1005, name: "Kilinochchi"},
    {id: 1006, name: "Kopay"},
    {id: 1007, name: "Manipay"},
    {id: 1008, name: "Nallur"},
    {id: 1009, name: "Point Pedro"},
    {id: 1010, name: "Udupiddy"},
    {id: 1011, name: "Vaddukkoddai"},
    {id: 1012, name: "Postal"},
  ],
  11 : [ // Vanni
    {id: 1101, name: "Mannar"},
    {id: 1102, name: "Mullaitivu"},
    {id: 1103, name: "Vavuniya"},
    {id: 1104, name: "Postal"},
  ],
  12 : [ // Batticaloa
    {id: 1201, name: "Batticaloa"},
    {id: 1202, name: "Kalkudah"},
    {id: 1203, name: "Padiruppu"},
    {id: 1204, name: "Postal"},
  ],
  13 : [ // Digamadulla
    {id: 1301, name: "Ampara"},
    {id: 1302, name: "Kalmunai"},
    {id: 1303, name: "Potuvil"},
    {id: 1304, name: "Sammanturai"},
    {id: 1305, name: "Postal"},
  ],
  14 : [ // Trincomalee
    {id: 1401, name: "Mutur"},
    {id: 1402, name: "Seruwila"},
    {id: 1403, name: "Trincomalee"},
    {id: 1404, name: "Postal"},
  ],
  15 : [ // Kurunegala
    {id: 1501, name: "Bingiriya"},
    {id: 1502, name: "Dambadeniya"},
    {id: 1503, name: "Dodangaslanda"},
    {id: 1504, name: "Galgamuwa"},
    {id: 1505, name: "Hiriyala"},
    {id: 1506, name: "Katugampola"},
    {id: 1507, name: "Kuliyapitiya"},
    {id: 1508, name: "Kurunegala"},
    {id: 1509, name: "Mawathagama"},
    {id: 1510, name: "Nikaweratiya"},
    {id: 1511, name: "Panduwasnuwara"},
    {id: 1512, name: "Polgahawela"},
    {id: 1513, name: "Wariyapola"},
    {id: 1514, name: "Yapahuwa"},
    {id: 1515, name: "Postal"},
  ],
  16 : [ // Puttalam
    {id: 1601, name: "Anamaduwa"},
    {id: 1602, name: "Chillaw"},
    {id: 1603, name: "Nattandiya"},
    {id: 1604, name: "Puttalam"},
    {id: 1605, name: "Wennappuwa"},
    {id: 1606, name: "Postal"},
  ],
  17 : [ // Anuradhapura
    {id: 1701, name: "Anuradhapura-East"},
    {id: 1702, name: "Anuradhapura-West"},
    {id: 1703, name: "Horowupotana"},
    {id: 1704, name: "Kalawewa"},
    {id: 1705, name: "Kekirawa"},
    {id: 1706, name: "Medawachchiya"},
    {id: 1707, name: "Mihintale"},
    {id: 1708, name: "Postal"},
  ],
  18 : [ // Polonnaruwa
    {id: 1801, name: "Medirigiriya"},
    {id: 1802, name: "Minneriya"},
    {id: 1803, name: "Polonnaruwa"},
    {id: 1804, name: "Postal"},
  ],
  19 : [ // Badulla
    {id: 1901, name: "Badulla"},
    {id: 1902, name: "Bandarawela"},
    {id: 1903, name: "Hali Ela"},
    {id: 1904, name: "Haputale"},
    {id: 1905, name: "Mahiyangane"},
    {id: 1906, name: "Passara"},
    {id: 1907, name: "Uva-Paranagama"},
    {id: 1908, name: "Welimada"},
    {id: 1909, name: "Wiyaluwa"},
    {id: 1910, name: "Postal"},
  ],
  20 : [ // Moneragala
    {id: 2001, name: "Bibile"},
    {id: 2002, name: "Moneragala"},
    {id: 2003, name: "Wellawaya"},
    {id: 2004, name: "Postal"},
  ],
  21 : [ // Ratnapura
    {id: 2101, name: "Balangoda"},
    {id: 2102, name: "Eheliyagoda"},
    {id: 2103, name: "Kalawana"},
    {id: 2104, name: "Kolonna"},
    {id: 2105, name: "Nivitigala"},
    {id: 2106, name: "Pelmadulla"},
    {id: 2107, name: "Rakwana"},
    {id: 2108, name: "Ratnapura"},
    {id: 2109, name: "Postal"},
  ],
  22 : [ // Kegalle
    {id: 2201, name: "Aranayake"},
    {id: 2202, name: "Dedigama"},
    {id: 2203, name: "Deraniyagala"},
    {id: 2204, name: "Galigamuwa"},
    {id: 2205, name: "Kegalle"},
    {id: 2206, name: "Mawanella"},
    {id: 2207, name: "Rambukkana"},
    {id: 2208, name: "Ruwanwella"},
    {id: 2208, name: "Yatiyantota"},
    {id: 2209, name: "Postal"},
  ],
}
